### ISSUE TITLE
希望增加自动申请PFX格式的证书

### ISSUE THREAD

**Issue by capsshift** [certd/certd#100]
一、问题描述

现在certd自动申请的证书是用于nginx的，解决了大部分问题，但是一些老的系统，需要使用PFX格式的证书，虽然可以去转换一下，还是太麻烦了，希望能加上这个功能。

### 效果截图

1. 期望效果

期望在下载页面，可以有PFX格式证书下载。

**Comment by greper** [comment]
1.24.3已支持
