### ISSUE TITLE
docker 项目没有arm64 版本 希望支持

### ISSUE THREAD

**Issue by Emtier** [certd/certd#102]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
docker 项目没有arm64 版本 希望支持
`root@linux:~# docker pull registry.cn-shenzhen.aliyuncs.com/handsfree/certd:latest
latest: Pulling from handsfree/certd
no matching manifest for linux/arm64/v8 in the manifest list entries`

**Comment by greper** [comment]
试试 1.22.4

**Comment by Emtier** [comment]
> 试试 1.22.4

收到
