### ISSUE TITLE
【BUG】windows服务器连接不上

### ISSUE THREAD

**Issue by a810439322** [certd/certd#107]
端口是3389，账号密码都没问题，选了windows服务器的选项，还是无法连接报超时，希望修复

**Comment by greper** [comment]
windows要安装openssh

**Comment by a810439322** [comment]
安装了openssh后果然可以啦，多谢大大

**Comment by 41369ly** [comment]
> windows要安装openssh

可以在弹窗中加一下提示吗？我也是遇到了这个问题来看Issues才发现要安装openssh
