### ISSUE TITLE
 添加域名解析出错

### ISSUE THREAD

**Issue by bchengwang** [certd/certd#108]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`
添加域名解析出错 Error: getaddrinfo EAI_AGAIN alidns.aliyuncs.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'alidns.aliyuncs.com'
}
### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 报错截图
![image](https://github.com/user-attachments/assets/44b078b7-f1d1-4139-92ef-b24a49ba2ee2)

![image](https://github.com/user-attachments/assets/78b701ad-722f-45cb-809f-f03b8d59b84e)

### 效果截图
`请贴出效果截图`

**Comment by greper** [comment]
运行certd的服务器， 设置一下dns地址， 223.5.5.5， 你服务器的dns解析阿里云域名ip有问题

**Comment by bchengwang** [comment]
> 运行certd的服务器， 设置一下dns地址， 223.5.5.5， 你服务器的dns解析阿里云域名ip有问题

感谢
