### ISSUE TITLE
主机授权那块能否增加个sock5代理的功能

### ISSUE THREAD

**Issue by Yiipanny** [certd/certd#111]
## 一、问题描述
很多国外主机国内不走代理连不上，ssh时不时被严重阻断
，因业务问题国内国外要同时部署证书，国内外分开部署certd有维护上的不便

### 复现步骤
上传证书到主机就是超时，无尽的超时，上传步骤又不能跳过，一次错误就要全部重试

所以希望主机授权那期望可选走代理，增加一个代理开关的选项
![image](https://github.com/user-attachments/assets/0df302a2-88e3-4ca5-aaa6-537d85218696)

**Comment by greper** [comment]
1.26.8 已支持
