### ISSUE TITLE
【需求】希望小小的优化一下流水线展示和搜索

### ISSUE THREAD

**Issue by a810439322** [certd/certd#113]
1. 流水线排序能不能支持自定义？这样的话我可以按组自定义排序了，而不是现在的默认按id或者时间排序

2. 流水线按名称搜索，可否改为模糊搜索？比如我的CLB相关的命名都有CLB，所以我就想输入CLB，搜索出所有CLB相关的证书流水线

**Comment by greper** [comment]
已支持

**Comment by a810439322** [comment]
> 已支持

出错啦，模糊查询会查出所有的流水线，哈哈
