### ISSUE TITLE
【BUG】CLB的监听器未开启SNI时，日志里面成功，但是证书未上传和配置，建议报错或者在哪里提醒一下

### ISSUE THREAD

**Issue by a810439322** [certd/certd#115]
![image](https://github.com/user-attachments/assets/e794cc2a-4472-4977-9906-8c720d1b70fb)

**Comment by a810439322** [comment]
![f95b2f6a16ee140808e73bf07afef81](https://github.com/user-attachments/assets/ef907b5a-22e6-4849-8e79-1cc8604d3c9e)
![a30cf859a0048f7eff5e010d9954e9c](https://github.com/user-attachments/assets/b58088fa-4f78-48a4-b8d1-6e1fe08245e0)

**Comment by greper** [comment]
已增加说明提示
