### ISSUE TITLE
能否有选项选择申请ECC ECDSA-WITH-SHA256 证书？现在默认是RSA证书

### ISSUE THREAD

**Issue by 6aink** [certd/certd#116]
能否有选项选择申请ECC ECDSA-WITH-SHA256 证书？现在默认是RSA证书

**Comment by Emtier** [comment]
同求

**Comment by Emtier** [comment]
- **RSA 证书**：
     sudo certbot --nginx -d example.com -d www.example.com
- **ECC 证书**：
     sudo certbot --nginx **--key-type ecdsa** -d example.com -d www.example.com
总的来说，申请 ECC 证书和 RSA 证书的区别仅在于命令中增加了 `--key-type ecdsa` 参数，其他步骤和配置都是相同的。

**Comment by gkl1368** [comment]
非常想要这个功能

**Comment by greper** [comment]
1.24.0已支持
