### ISSUE TITLE
新网（https://www.xinnet.com/)上注册的域名，应该怎么配置参数

### ISSUE THREAD

**Issue by magicGeng** [certd/certd#118]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
新网上注册的域名，
有些参数不知道该怎么填；
<img width="915" alt="f503c62f9a6f63cf7eeed193b9c3e53" src="https://github.com/user-attachments/assets/309c3f18-2314-4510-ba22-b3cf71f4fe0a">

https://go-acme.github.io/lego/dns/ 这个列表里面也没有
<img width="1169" alt="e841ea7bd7bda91a33f04fbf037835f" src="https://github.com/user-attachments/assets/1aa5c5d6-a3c1-4b52-ab27-7f8e7d861bed">

### 复现步骤
如果当成阿里云处理的话，环境变量填成阿里云的access_key和secret_key；执行会报错。

### 报错截图
<img width="950" alt="70c122a3745f1cf03d047deeaaf2d94" src="https://github.com/user-attachments/assets/8bdfbab5-2c0c-4341-ad39-a3eb79840750">

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
期望能够实现新网上注册的域名，也能生成证书

**Comment by greper** [comment]
新网普通会员用户不支持API接口创建和删除解析记录。这年头居然还有不支持api接口的。。。（问客服说只有代理商账号才有api接口，这门槛就高了）

建议你这边把dns服务器改成阿里云或者腾讯云的， 或者把域名转出去
![image](https://github.com/user-attachments/assets/7efa1bc6-9c71-4f4a-85f1-56229a221ff7)

**Comment by greper** [comment]
1.36.22 已支持新网 直接dns解析
