### ISSUE TITLE
Certd v1.23.1 无法批量删除执行历史记录

### ISSUE THREAD

**Issue by Emtier** [certd/certd#119]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
`Certd v1.23.1 无法批量删除执行历史记录`

### 复现步骤
`进入执行历史记录-多选记录-点击下方批量删除-显示成功但是实际不成功`

### 报错截图
<img width="347" alt="截屏2024-08-08 18 13 21" src="https://github.com/user-attachments/assets/5784f3c4-b0c7-41cf-9b6a-77024813b297">

**Comment by greper** [comment]
1.24.0已修复
