### ISSUE TITLE
timeout of 5000ms exceeded

### ISSUE THREAD

**Issue by vipnetant** [certd/certd#120]
一、问题描述
每次“手动触发”更新证书后，右上角会报错“timeout of 5000ms exceeded”
等证书更新成功后自动消失。

二、问题版本
image: registry.cn-shenzhen.aliyuncs.com/handsfree/certd:latest
版本：v1.23.1

三、报错截图
![image](https://github.com/user-attachments/assets/eefac9db-db33-4c75-ae58-514fe5445b04)

**Comment by greper** [comment]
我这边没有复现

**Comment by werfei** [comment]
我遇到了同样的问题

**Comment by greper** [comment]
1.24.3已调整为10s
