### ISSUE TITLE
无法pull 1.22.1之后的镜像版本

### ISSUE THREAD

**Issue by TaylorEevee** [certd/certd#124]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)
docker pull registry.cn-shenzhen.aliyuncs.com/handsfree/certd:latest
Trying to pull repository registry.cn-shenzhen.aliyuncs.com/handsfree/certd ... 
Pulling repository registry.cn-shenzhen.aliyuncs.com/handsfree/certd
Error: image handsfree/certd:latest not found

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`
pull镜像时显示没有镜像
### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`
pull镜像时显示没有镜像

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`

**Comment by greper** [comment]
armv7?

**Comment by TaylorEevee** [comment]
> armv7?

我机器是x64的

**Comment by greper** [comment]
那不应该啊，你发一下截图

**Comment by greper** [comment]
试试dockerhub 的  
docker pull greper/certd:latest

**Comment by TaylorEevee** [comment]
> 试试dockerhub 的 docker pull greper/certd:latest

额
![image](https://github.com/user-attachments/assets/a729d942-4567-4234-a611-cc1a2e782a4a)

**Comment by TaylorEevee** [comment]
> > 试试dockerhub 的 docker pull greper/certd:latest
> 
> 额 ![image](https://private-user-images.githubusercontent.com/75898916/365613427-a729d942-4567-4234-a611-cc1a2e782a4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NzgwNjksIm5iZiI6MTcyNTg3Nzc2OSwicGF0aCI6Ii83NTg5ODkxNi8zNjU2MTM0MjctYTcyOWQ5NDItNDU2Ny00MjM0LWE2MTEtY2MxYTJlNzgyYTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDEwMjkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NDc2OGMxNGVhNmQ5MGMwZTIzN2JiMjc5NWIxYzkwZjhhMGJjZDYxMDExYzYzNjBhOTdlMGFmNTNhMGI5NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y7QU3Xw8bzccJtAJQrGXmLUvlSs3-KiPCOEYEV-Xj5Y)

dockerhub的显示没有签名

**Comment by greper** [comment]
x86和armv8 使用正常的版本号
armv7 使用armv7  或 [version]-armv7
![image](https://github.com/user-attachments/assets/870f865c-ff0f-4913-b789-0c8de06ee0f3)

再试试，如果还是不行请重新提交issue
