### ISSUE TITLE
主域名与泛域名同时提交在腾讯云dns上重复添加TXT解析

### ISSUE THREAD

**Issue by QiXingQXX** [certd/certd#125]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

### 复现步骤
![QQ20240810-222651](https://github.com/user-attachments/assets/8d0c2e9a-2aa0-429e-9fdb-e0edcab9a238)
![QQ20240810-222510](https://github.com/user-attachments/assets/62e45ced-1f89-4e4f-b5f4-e1b1d6f53013)

**Comment by Emtier** [comment]
泛域名本身就需要两个TXT解析

**Comment by QiXingQXX** [comment]
> 泛域名本身就需要两个TXT解析

主要是最后失败了，提示就是未找到解析，我都从第三方网站查过有解析了😰

**Comment by Emtier** [comment]
> > 泛域名本身就需要两个TXT解析
> 
> 主要是最后失败了，提示就是未找到解析，我都从第三方网站查过有解析了😰

这两个记录是否是之前申请证书时候的遗留，还有从第三方网站查到过，你自己的dns后台查不到新的记录吗

**Comment by greper** [comment]
1.24.0 再试试
