### ISSUE TITLE
建议增加对Google SSL证书的支持

### ISSUE THREAD

**Issue by xiaoweicloud** [certd/certd#133]
问题描述
在使用certd的过程中，我发现目前工具尚未支持Google SSL证书的签发。相比其他免费品牌的SSL证书，Google SSL证书在以下几个方面有显著优势：

OCSP节点支持：Google SSL证书在中国大陆有OCSP节点覆盖，这意味着在国内的网络环境下，证书验证速度更快，稳定性更高。其他免费品牌的SSL证书在这方面可能存在延迟问题，尤其是在网络条件较差的情况下。

品牌信誉度：Google作为全球领先的互联网公司，其SSL证书在用户心目中具有较高的信誉和信任度。为用户提供Google证书选项，有助于提高网站的安全性和访问者对网站的信任。

提升用户体验：Google SSL证书在中国大陆的OCSP节点支持，能够减少证书验证的延迟，从而提高用户的访问体验，特别是在对访问速度和稳定性有高要求的应用场景中。

建议增加对Google SSL证书的支持，以便为用户提供更多优质的选择，满足更广泛的需求。

**Comment by greper** [comment]
1.24.0已支持
