### ISSUE TITLE
执行远程主机脚本命令错误

### ISSUE THREAD

**Issue by StrideLeo** [certd/certd#136]
## 问题描述
`在威联通Container Station中部署了certd，版本v1.23.1；
主机在内网的ip是192.168.2.3，平时用putty等工具通过22端口能够正常登录ssh；
我在docker容器中挂载了威联通的证书存放文件夹：/mnt/HDA_ROOT/.config/stunnel:/etc/stunnel；
在“上传证书到主机”任务中勾选了“仅复制到当前主机”；测试“证书申请任务”和“上传到主机”任务都没问题；
因为威联通系统中ssl证书只有一个stunnel.pem，是把证书和密钥拼接到一起形成的；
所以上传证书任务后我设定了继续执行脚本命令
“cp /etc/stunnel/stunnel.pem /etc/stunnel/stunnel.pem.bak && cat /etc/stunnel/backup.key /etc/stunnel/backup.crt > /etc/stunnel/stunnel.pem && /etc/init.d/stunnel.sh restart && /etc/init.d/Qthttpd.sh restart”
结果测试时提示“执行远程主机脚本命令错误”

## 报错截图
![image](https://github.com/user-attachments/assets/31ed7f62-366b-428a-960c-94c0b93cf892)
![image](https://github.com/user-attachments/assets/781de808-3a4c-420c-8bde-05e52afae102)

**Comment by StrideLeo** [comment]
威联通系统是QTS QTS 5.1.8.2823，最新版本了

```
[~] # ssh -Q HostKeyAlgorithms
ssh-ed25519
ssh-ed25519-cert-v01@openssh.com
sk-ssh-ed25519@openssh.com
sk-ssh-ed25519-cert-v01@openssh.com
ecdsa-sha2-nistp256
ecdsa-sha2-nistp256-cert-v01@openssh.com
ecdsa-sha2-nistp384
ecdsa-sha2-nistp384-cert-v01@openssh.com
ecdsa-sha2-nistp521
ecdsa-sha2-nistp521-cert-v01@openssh.com
sk-ecdsa-sha2-nistp256@openssh.com
sk-ecdsa-sha2-nistp256-cert-v01@openssh.com
webauthn-sk-ecdsa-sha2-nistp256@openssh.com
ssh-rsa
ssh-rsa-cert-v01@openssh.com
rsa-sha2-256
rsa-sha2-256-cert-v01@openssh.com
rsa-sha2-512
rsa-sha2-512-cert-v01@openssh.com
[~] # ssh -V
OpenSSH_9.8p1, OpenSSL 1.1.1t  7 Feb 2023

```

**Comment by greper** [comment]
升级1.24.0 再试试

**Comment by StrideLeo** [comment]
> 升级1.24.0 再试试

最新版已解决，谢谢
