### ISSUE TITLE
期望增加密钥算法自主选择ECC/RSA

### ISSUE THREAD

**Issue by jiuyue52** [certd/certd#137]
## 一、问题描述
期望增加自助选择密钥算法，自主选择ECC / RSA加密，类似1panel面板那样

### 复现步骤
如1Panel面板那样

### 期望效果截图
![S40822-15572559_com android chrome](https://github.com/user-attachments/assets/decffa14-e787-47a9-917b-b884a3dba376)

**Comment by greper** [comment]
1.24.0已支持
