### ISSUE TITLE
腾讯云CDN已全面升级为边缘安全加速平台(TencentCloud EdgeOne, 简称 EdgeOne)

### ISSUE THREAD

**Issue by xlsys** [certd/certd#138]
## 一、问题描述
腾讯云CDN已全面升级为边缘安全加速平台(TencentCloud EdgeOne, 简称 EdgeOne)

### 报错截图
`请贴出报错日志截图`
![图片](https://github.com/user-attachments/assets/ad93d355-47b6-40a3-8a8c-99c60b385b4a)

**Comment by greper** [comment]
1.24.0已支持
