### ISSUE TITLE
支持ftp传输证书方式

### ISSUE THREAD

**Issue by greper** [certd/certd#141]

**Comment by agczsz** [comment]
最好做到能把旧证书替换下来，我目前确实很需要这个功能，给你们点赞，加急开发

**Comment by greper** [comment]
ftp的正在开发了，
你的具体是什么系统需要证书？

**Comment by agczsz** [comment]
> ftp的正在开发了， 你的具体是什么系统需要证书？

康乐面板，这个老面板没let的证书自动申请，只能手动上传替换，而现在1年免费ssl都没了，要续期很麻烦，所以需要这个自动替换老证书

**Comment by greper** [comment]
1.24.1已支持
