### ISSUE TITLE
支持cdnfly系统的证书自动上传和管理V

### ISSUE THREAD

**Issue by ji233-Sun** [certd/certd#145]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`
cdnfly是一个非常常见的CDN系统，很多idc的CDN系统都用的是这套，支持cdnfly即可支持特别多的CDN
API文档：
https://www.kancloud.cn/jason22/manual/2540537

**Comment by greper** [comment]
1.24.1已支持
