### ISSUE TITLE
[bug]基于复制工作流新申请的证书首页不显示生效日期及配置重复

### ISSUE THREAD

**Issue by vseal001** [certd/certd#149]
问题描述：
1、证书有效期不显示；
2、修改新复制的工作流（如域名等），手动执行是生效的，退回首页后会出现修改的配置复原（即修改失效，修改后的工作流与原复制基础工作流任务一模一样，*修改任务名称也无用）；
复现步骤v1.24.1：
1、复制原有的证书申请任务工作流（基于Let's encrypt*Cloud flare)；
2、更改申请域名并保存；
3、点击触发手动执行；
4、返回首页查看：我的流水线；
![图片](https://github.com/user-attachments/assets/458d9951-1cfa-4a18-9005-83a0214f71cc)

**Comment by vseal001** [comment]
配置还原情况如下：
1、修改后的执行情况：
![93451a1e53294291d5f0a7080ede895](https://github.com/user-attachments/assets/162c9925-cf25-4ee8-97cd-842a1e1ac4a4)

2、刷新页面h后（配置被还原）：
![390cfa0bf1dbc3106fd6ea60803360d](https://github.com/user-attachments/assets/b97e9fb3-5cfd-4766-88e9-35e77c527e48)
![d73239e02a13f516f86e25ed1c0691b](https://github.com/user-attachments/assets/a5154fee-0da5-44c8-8887-8932ea71dcc7)

3、返回首页，复制源的标题被改动、证书日期居然被刷新了：
![d05fd155d6a158a630df22c9d2cbe5b](https://github.com/user-attachments/assets/b16b3d07-791a-474e-a59b-31eb43329801)

**Comment by greper** [comment]
1.24.3已修复
