### ISSUE TITLE
建议增加ajax请求时间[v]

### ISSUE THREAD

**Issue by wujingke** [certd/certd#153]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
部署在koyeb上   访问系统ui的时候经常超时
<img width="386" alt="image" src="https://github.com/user-attachments/assets/29283388-c9cc-48fe-b89c-4b8431185928">

**Comment by wujingke** [comment]
#120   一样的问题   原因是前端ajax超时设置的5秒   部署在外网的服务器有时候因为网络问题导致超时了        建议设置为15-20秒

**Comment by greper** [comment]
1.24.3已调整为10s
