### ISSUE TITLE
SignatureDoesNotMatchError: Specified signature is not matched with our calculation. server string to sign 

### ISSUE THREAD

**Issue by hetl** [certd/certd#154]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`

**Comment by hetl** [comment]
一、问题描述
在docker下部署最新的certd v1.24.1版本，使用阿里云的dns时候抛出了SignatureDoesNotMatchError: Specified signature is not matched with our calculation. server string to sign 错误

报错截图
![image](https://github.com/user-attachments/assets/f6aaddc2-cf59-4d95-869a-889f2e19781c)

**Comment by greper** [comment]
确认你的accessKey 和accessSecret没有填错
