### ISSUE TITLE
执行远程主机脚本命令 windows服务器，输入多行命令仅执行第一行命令

### ISSUE THREAD

**Issue by haorizilai** [certd/certd#157]
![ad741833ad11409cdf63979464a72dc](https://github.com/user-attachments/assets/6eb43258-527d-4916-a177-0dc636059d1c)

![3a5863db75979e2e6b22d8e1055684e](https://github.com/user-attachments/assets/5a956a3f-5abd-4478-8f35-9940347806ba)

分别两个dir命令，但是只有第一行命令生效，第二行命令未执行。

**Comment by greper** [comment]
1.24.3已支持， 实际上使用 && 拼接多行命令的方式
