### ISSUE TITLE
部署到多吉云报错

### ISSUE THREAD

**Issue by nmgliangwei** [certd/certd#163]
部署到多多吉云，会报错，但是多吉云那边其实已经上传并绑定了。
![IMG_20240908_212404.jpg](https://github.com/user-attachments/assets/c7c28938-8735-4990-a38c-ec7f0df73aaf)

**Comment by greper** [comment]
每次都这样吗？

**Comment by nmgliangwei** [comment]
有一个域名每次都这样，同一个部署流程有个www的没事，不带www的就报错。但是其它域名同样部署到多吉云，带不带www都不会出现这个错

**Comment by greper** [comment]
这个建议你咨询一下多吉云那边 看一下这个域名为什么会这样

**Comment by nmgliangwei** [comment]
ok

**Comment by greper** [comment]
1.24.4 增加报错忽略参数
