### ISSUE TITLE
上传证书到服务商时，域名证书【from：申请证书】选项不可用

### ISSUE THREAD

**Issue by 1zhiye** [certd/certd#171]
您好，请问您的这个域名证书选项里内容（域名证书【from：申请证书】）是从那里获得的，我在第一步申请完证书后，第二步上传证书到阿里云时，这是必填项，但是我的待选框里无内容。另外我已手动执行了第一步申请证书是成功的
![1726219263229](https://github.com/user-attachments/assets/509a90b3-6c30-41de-8212-c5b3bbd73d32)
![1726219313518](https://github.com/user-attachments/assets/737418de-552e-4c89-b90e-8f3d17e69603)
![1726219338118](https://github.com/user-attachments/assets/051ca3c0-e3df-4328-8753-872cca069e77)

**Comment by Emtier** [comment]
申请证书和部署证书需要在一条流水线里面才能进行部署

**Comment by greper** [comment]
要在证书申请任务后面的阶段创建新任务
![image](https://github.com/user-attachments/assets/b82d1baa-24c0-405e-943b-65cef0c1a727)

**Comment by 1zhiye** [comment]
当我选择证书申请（lego）时，我正是在新阶段里添加上传证书任务， 保证是串行而不是并行，但是证书的待选框里仍然是无内容的。但我选择证书申请（JS版）后，就一切正常了。我在官方Demo中（https://certd.handsfree.work/）也发现存在这个问题，我新建了两项任务（lego和js），其中js正常，lego异常，测试账号为：20240918，密码为：20240918。
![1726640115357](https://github.com/user-attachments/assets/f6b66dbb-0f19-4593-aff2-29da5a774d42)

**Comment by greper** [comment]
噢噢 知道了

**Comment by tanher** [comment]
解决了吗？

**Comment by greper** [comment]
1.25.4已解决
