### ISSUE TITLE
如何进行迁移

### ISSUE THREAD

**Issue by NickNameIsNull** [certd/certd#173]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
当前certd已部署在服务器的docker中。
现在由于原服务器需要进行重装，如何保留当前certd已有配置能进行丝滑迁移。
可否通过保存当前已有容器，进行迁移

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
能够在保证当前已有certd配置的情况下，进行服务器之间的迁移。

**Comment by Emtier** [comment]
只需要找到映射的certd文件夹 备份下来 然后新的服务器恢复映射的certd文件夹就可以无损恢复了

**Comment by Emtier** [comment]
volumes:
      #   ↓↓↓↓↓ -------------------------------------------------------- 数据库以及证书存储路径,默认存在宿主机的/data/certd/目录下，【您需要定时备份此目录，以保障数据容灾】
      - /data/certd:/app/data

**Comment by NickNameIsNull** [comment]
感谢，已完成迁移。
