### ISSUE TITLE
K8S Ingress证书部署支持insecure-skip-tls-verify V

### ISSUE THREAD

**Issue by superchaos** [certd/certd#178]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`
K8S Ingress证书部署是否可以支持insecure-skip-tls-verify
由于自签名证书，外部访问地址有可能存在映射导致证书校验失败，需要能跳过

**Comment by greper** [comment]
insecure-skip-tls-verify
这是cluster自己的配置吧
