### ISSUE TITLE
缺少文件，无法部署

### ISSUE THREAD

**Issue by ivoidcat** [certd/certd#182]
<img width="1626" alt="image" src="https://github.com/user-attachments/assets/2a08bade-75a0-4eff-8547-7a5b817eb6f8">
现在手动部署遇到这个问题，环境跟docker里是一样的

**Comment by greper** [comment]
根路径运行 lerna run build

**Comment by ivoidcat** [comment]
根目录已经执行了
npm run init

**Comment by ivoidcat** [comment]
是不是不能在m1电脑下面运行啊

**Comment by ivoidcat** [comment]
大佬，爱发电了，希望看看

**Comment by BylethC** [comment]
> 大佬，爱发电了，希望看看

构建完成后，在根目录用官方给的 pnpm run start 无法启动，改为在根目录使用 pnpm --filter @certd/ui-server start，成功启动了
