### ISSUE TITLE
点击按钮出现报错

### ISSUE THREAD

**Issue by geteshi** [certd/certd#183]
### 复现步骤
点击下面这几个按钮
![image](https://github.com/user-attachments/assets/689eea6a-d6c1-415e-ad01-802fb827b975)
都会出现这个问题

### 报错截图

![image](https://github.com/user-attachments/assets/61602125-f727-4bf4-b611-0b1c258c2a25)

**Comment by greper** [comment]
部署的首页有缓存，导致请求的资源错误，具体要看你部署的环境
