### ISSUE TITLE
上传证书到主机出现报错

### ISSUE THREAD

**Issue by geteshi** [certd/certd#184]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
运行到上传证书到主机出现 `ValidateException: id不能为空`，然后编辑任务，选择`域名证书`里面的内容也是空的

### 复现步骤
运行到上传证书到主机

### 报错截图
![image](https://github.com/user-attachments/assets/2fd4e1eb-c6ea-49c9-a9fa-3e198e3d405d)

**Comment by greper** [comment]
你应该是先创建了任务，之后把access授权在授权管理页面删掉了。导致这里获取不到

到上传任务里面 重新选择一下access授权即可

**Comment by greper** [comment]
域名证书内容为空 是不是你把证书申请任务也删除过？

**Comment by greper** [comment]
新版本 上传到主机插件 不再支持复制到本机， 如果需要复制到本机，请使用复制到本机插件
