### ISSUE TITLE
支持腾讯云COS证书部署 V

### ISSUE THREAD

**Issue by ivoidcat** [certd/certd#188]
现在只是支持腾讯云CDN，期待支持COS

**Comment by greper** [comment]
看了一下 腾讯云cos的自定义源站域名证书 没有提供接口 好像做不了

**Comment by ivoidcat** [comment]
应该是可以，因为之前用httpsok，他就有这个功能
<img width="1157" alt="image" src="https://github.com/user-attachments/assets/f873e549-6bd6-45ac-9217-909447c43eaa">

**Comment by ivoidcat** [comment]
<img width="1200" alt="image" src="https://github.com/user-attachments/assets/77dd6e59-f44f-4dfb-9778-b4442052ff02">

**Comment by ivoidcat** [comment]
https://cloud.tencent.com/document/api/400/91661
https://cloud.tencent.com/document/api/400/91667

这两个链接不知道是不是

**Comment by greper** [comment]
已支持
