### ISSUE TITLE
这是重新申请证书把？要重新部署

### ISSUE THREAD

**Issue by find-xposed-magisk** [certd/certd#19]
而不是不变KEY续期吧？

**Comment by greper** [comment]
ssl证书续期 都是重新申请新的证书吧
没有听说过可以不变key续期的，你有相关资料和链接吗

**Comment by find-xposed-magisk** [comment]
没有哦，哈哈、折腾了一天看了都是重新部署的资料

**Comment by greper** [comment]
嗯 因为过期时间是写死在证书里面的，验证也是本地直接可以验证的，所以不可能不换证书直接续期的

**Comment by greper** [comment]
如此一来，自动部署就非常重要

**Comment by find-xposed-magisk** [comment]
环境不复杂的就舒服了。
我的环境很复杂，国内一个cdn，国外用CF，自己还自建了cdn，只能手工换
另外，腾讯云的上传证书好像有问题。
昨天试了一个全局KEY和一个子账户（只有ssl证书权限、现开）的，都提示tokenID不存在，我以为写反了，换了位置也是一样

**Comment by greper** [comment]
嗯 是有点问题，我修复一下

**Comment by greper** [comment]
1.1.6已修复

**Comment by find-xposed-magisk** [comment]
![image.png](https://pic6.58cdn.com.cn/nowater/webim/big/n_v2d41b3e4de48043d6a91670c2482962d4.png)
不能读取域名

**Comment by greper** [comment]
![image](https://github.com/certd/certd/assets/1687298/5a14cc86-b874-435b-9611-5cd386b24c3d)
 前面有没有配置申请证书？

![image](https://github.com/certd/certd/assets/1687298/8f788a96-d2e1-476d-bb71-9a18c779e48a)
这里是否有值？

**Comment by find-xposed-magisk** [comment]
奇怪 什么都改又成功了 
![image.png](https://pic2.58cdn.com.cn/nowater/webim/big/n_v208d83a20d00f4e0dace98aa51081dab5.png)
