### ISSUE TITLE
腾讯云cdn部署ssl证书失败

### ISSUE THREAD

**Issue by l9rw** [certd/certd#190]
腾讯云cdn，ssl证书能正常上传到证书管理里，但是无法部署到域名

**Comment by Emtier** [comment]
提供报错内容啊

**Comment by l9rw** [comment]
没有报错，接口提示成功，但是实际没有改。把腾讯cdn证书删掉，再跑任务就能复现。
<img width="865" alt="image" src="https://github.com/user-attachments/assets/2d434b67-458c-4265-9df1-90aacdaff283">

**Comment by greper** [comment]
无法复现，是最新版的certd吗

**Comment by greper** [comment]
你是用的国际版吗

**Comment by greper** [comment]
试试腾讯云cdnv2版
![image](https://github.com/user-attachments/assets/e7072bb0-2646-49b0-9292-70dd4099914d)

**Comment by l9rw** [comment]
v2可以了，谢谢
