### ISSUE TITLE
定时脚本显示时间bug

### ISSUE THREAD

**Issue by vipnetant** [certd/certd#194]
## 一、问题描述
“编辑触发器”时显示的“定时脚本”时间是错误的，我设置了每周六X点，但显示成“每天”了。

### 报错截图
![B9KZ)`}~2@1E5`DXX4P_4@7](https://github.com/user-attachments/assets/4ca22845-c476-436b-9ce7-8641a5f32f00)

**Comment by greper** [comment]
1.26.12已优化
