### ISSUE TITLE
管理其他用户流水线会修改流水线归属用户ID？ V

### ISSUE THREAD

**Issue by coolxitech** [certd/certd#197]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
修改其他用户的流水线会更新流水线的用户ID

### 复现步骤
管理员身份修改普通用户的流水线，在流水线列表会看到用户ID变成管理员ID的1.

### 报错截图
无报错
### 效果截图
无截图
#### 1. 期望效果
不变更流水线归属用户

**Comment by greper** [comment]
1.26.4 已修复
