### ISSUE TITLE
Google EAB密钥有效期7天 V

### ISSUE THREAD

**Issue by LjyLab** [certd/certd#198]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
Error: Unknown external account binding (EAB) key. This may be due to the EAB key expiring which occurs 7 days after creation. You can generate a new key by following https://cloud.google.com/certificate-manager/docs/public-ca-tutorial#request-key-hmac

未知的外部帐户绑定（EAB）密钥。这可能是由于EAB密钥在创建后7天发生。您可以通过关注https://cloud.google.com/certificate-manager/docs/public-ca-tutorial#request-key-hmac来生成新密钥

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 报错截图
`请贴出报错日志截图`
![abd8a41e2a2b90c831f6302ffb47052e](https://github.com/user-attachments/assets/cec1cdf7-81c8-4b27-a4c6-7136185995e6)

### 效果截图
`请贴出效果截图`

**Comment by greper** [comment]
不要更换邮箱

**Comment by LjyLab** [comment]
爱你! mua~
