### ISSUE TITLE
编辑授权弹窗点确定按钮无法关闭弹窗

### ISSUE THREAD

**Issue by mafeifan** [certd/certd#2]
首先感谢提供了这个牛逼的工具
测试 https://certd.docmirror.cn/#/detail 后发现个小问题，
如图
![](https://pek3b.qingstor.com/hexo-blog/QQ%E5%9B%BE%E7%89%8720210830215027.png)

另外还有个问题，API密钥，id和key属于非常重要的信息，怎么确定https://certd.docmirror.cn不会保存，还有个小建议，弹窗下面加上申请密钥的链接和说明，如果腾讯云的密钥管理地址 https://console.cloud.tencent.com/cam/capi

**Comment by greper** [comment]
https://certd.docmirror.cn 不会提交任何数据出去。
你可以打开网站之后，断网操作。
也可以按F12，查看网络请求情况。
或者你可以填假的id和key，导出包后再本地修改为正确的数据

**Comment by greper** [comment]
请使用v2版本
