### ISSUE TITLE
建议增加对NameSilo的DNS解析支持

### ISSUE THREAD

**Issue by yggcwx** [certd/certd#203]
### 问题描述
目前自动申请证书流程里，支持的DNS解析提供方，并不包含Namesilo，导致这家注册的域名无法申请证书。

### 期望效果
这家的域名既便宜又丰富，使用人数众多，建议后续版本尽快支持。

**Comment by origami-owo** [comment]
可以使用lego

**Comment by greper** [comment]
已支持

**Comment by yggcwx** [comment]
> 已支持

衷心感谢您的不懈努力！
