### ISSUE TITLE
建议优化certd菜单层级和逻辑

### ISSUE THREAD

**Issue by Emtier** [certd/certd#204]
1.现在certd的餐单有侧边栏模式 也有选择框模式，重复了，可以进行优化，
2.部分菜单比如：证书自动化里面的 账号信息 邮件设置可以移动到右上角用户名信息下作为二级菜单使用 
3.系统配置也管理也可以优化进入右上角管理员按钮
4.右上文档/源码可以优化进入 实用教程里

**Comment by greper** [comment]
1.26.4 已优化
