### ISSUE TITLE
希望支持自动部署到百度智能云 V

### ISSUE THREAD

**Issue by jason1235** [certd/certd#212]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 问题描述
`希望支持自动部署到百度智能云`
有相关接口可以使用 https://cloud.baidu.com/doc/CDN/s/qjzuz2hp8

**Comment by greper** [comment]
1.26.12 已支持
