### ISSUE TITLE
定时器格式的困扰

### ISSUE THREAD

**Issue by bcdi** [certd/certd#220]
譬如 每周日的凌晨3点，执行一次任务，显示成

    0 0 3 ? * 0

正确的应该为

    0 3 * * 0

![Screenshot 2024-10-23 at 14 41 53](https://github.com/user-attachments/assets/6e9bb396-f936-4953-bc77-656007cd4ff9)

**Comment by bcdi** [comment]
#194

**Comment by greper** [comment]
已优化
1、增加下次触发时间的显示，可以验证自己设置的是否正确
2、反显时不再固定显示每天按钮
