### ISSUE TITLE
【老证书清理】希望在部署成功后，可选把之前的老证书删掉，或者隔一天删掉之类的

### ISSUE THREAD

**Issue by a810439322** [certd/certd#222]
不然平台会一直有提醒
![d786533b55abfb8fdd21ec596d21544](https://github.com/user-attachments/assets/0ab90074-f5b0-4494-b957-d774fcee11f3)
![9c3e507dce9b69a58299fad72a60d16](https://github.com/user-attachments/assets/a7cae2d3-1322-4a56-930f-60c01ea73a97)

**Comment by greper** [comment]
1.26.15 已支持 
https://certd.docmirror.cn/guide/use/tencent/
