### ISSUE TITLE
能否增加上海云盾和白山云的支持

### ISSUE THREAD

**Issue by edu-hui** [certd/certd#225]
1. 期望效果
支持上海云盾和白山云的自动部署
https://www.yundun.com/

**Comment by edu-hui** [comment]
https://www.baishan.com/

**Comment by edu-hui** [comment]
[证书新增修改.pdf](https://github.com/user-attachments/files/17530932/default.pdf)
白山云api文档

**Comment by greper** [comment]
> [证书新增修改.pdf](https://github.com/user-attachments/files/17530932/default.pdf) 白山云api文档

1、文档缺少token获取方式
2、无法注册，没办法测试

**Comment by greper** [comment]
baoshanyun已支持
