### ISSUE TITLE
[BUG]首页头像同步异常V

### ISSUE THREAD

**Issue by carolcoral** [certd/certd#230]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
更新到`2.17.0`版本后，用户头像可以添加并更新了，但是更新头像后首页的头像无法同步，刷新页面也不生效

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 报错截图
<img width="1447" alt="image" src="https://github.com/user-attachments/assets/005a7aa0-b4d2-4ecc-9795-453034a8671b">
<img width="1467" alt="image" src="https://github.com/user-attachments/assets/e2e6ff13-5162-43ab-bf06-b2550b8f3a7c">

### 效果截图
`请贴出效果截图`

**Comment by greper** [comment]
1.27.2已修复
