### ISSUE TITLE
[Feature]顶部导航栏展示开关控制V 

### ISSUE THREAD

**Issue by carolcoral** [certd/certd#231]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
顶部导航栏展示开关控制。目前的顶部导航栏没有自动刷新功能，每次在别的页面更新的信息，切换回原来的tab后也无法自动同步，并且影响美观，建议可以加上开关控制是否需要展示

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
<img width="909" alt="image" src="https://github.com/user-attachments/assets/346d5417-851d-46b6-8b3c-704e80a58aa6">
#### 2. 实际效果
<img width="973" alt="image" src="https://github.com/user-attachments/assets/9467dc3c-7cc0-4600-8560-739ff7136b1c">

**Comment by greper** [comment]
目前改成了点击tab页签自动刷新
