### ISSUE TITLE
自定义js脚本如何获取证书数据

### ISSUE THREAD

**Issue by newbeea** [certd/certd#232]
感谢开源
## 一、问题描述
请问 自定义js脚本如何使用，有没有脚本demo，如何获取证书数据，this.cert 好像不行, this指针貌似取不到想要的值
感谢

**Comment by greper** [comment]
自定义js脚本还没有添加插件输入参数 我等会加一个

**Comment by greper** [comment]
通过 this.ctx.self.cert 可以获取

其中
```js
ctx = {
  CertReader: typeof CertReader;
  self: CustomScriptPlugin;
 //流水线定义
  pipeline: Pipeline;
  //步骤定义
  step: Step;
  //日志
  logger: Logger;
  //当前步骤输入参数跟上一次执行比较是否有变化
  inputChanged: boolean;
  //授权获取服务
  accessService: IAccessService;
  //邮件服务
  emailService: IEmailService;
  //cname记录服务
  cnameProxyService: ICnameProxyService;
  //插件配置服务
  pluginConfigService: IPluginConfigService;
  //流水线上下文
  pipelineContext: IContext;
  //用户上下文
  userContext: IContext;
  //http请求客户端
  http: HttpClient;
  //文件存储
  fileStore: FileStore;
  //上一次执行结果状态
  lastStatus?: Runnable;
  //用户取消信号
  signal: AbortSignal;
  //工具类
  utils: typeof utils;
  //用户信息
  user: UserInfo;
}
```

**Comment by newbeea** [comment]
> 通过 this.ctx.self.cert 可以获取
> 
> 其中
> 
> ```js
> ctx = {
>   CertReader: typeof CertReader;
>   self: CustomScriptPlugin;
>  //流水线定义
>   pipeline: Pipeline;
>   //步骤定义
>   step: Step;
>   //日志
>   logger: Logger;
>   //当前步骤输入参数跟上一次执行比较是否有变化
>   inputChanged: boolean;
>   //授权获取服务
>   accessService: IAccessService;
>   //邮件服务
>   emailService: IEmailService;
>   //cname记录服务
>   cnameProxyService: ICnameProxyService;
>   //插件配置服务
>   pluginConfigService: IPluginConfigService;
>   //流水线上下文
>   pipelineContext: IContext;
>   //用户上下文
>   userContext: IContext;
>   //http请求客户端
>   http: HttpClient;
>   //文件存储
>   fileStore: FileStore;
>   //上一次执行结果状态
>   lastStatus?: Runnable;
>   //用户取消信号
>   signal: AbortSignal;
>   //工具类
>   utils: typeof utils;
>   //用户信息
>   user: UserInfo;
> }
> ```

感谢回复，好像不行呢
![image](https://github.com/user-attachments/assets/ca6a35cc-cb0f-4505-ae21-34a58fcf01c7)

**Comment by greper** [comment]
哦，没有this，直接ctx.self.cert

**Comment by newbeea** [comment]
> 哦，没有this，直接ctx.self.cert

可以了，感谢感谢

**Comment by greper** [comment]
https://certd.docmirror.cn/guide/use/custom-script/
这里有文档示例
