### ISSUE TITLE
[BUG] 部署至阿里云任意云资源任务一直卡在检查，实际已经成功

### ISSUE THREAD

**Issue by imluyu** [certd/certd#233]
![image](https://github.com/user-attachments/assets/e9367dc7-6c22-4f50-8e9f-2d1fcea97770)

选择的是前置步骤中上传的证书，不知道是不是因为这个导致检查不成功
![image](https://github.com/user-attachments/assets/ce65bf79-9a0d-491f-92f8-e78c05185a4c)

**Comment by greper** [comment]
奇怪 都success 怎么还没结束任务，我修复一下

**Comment by greper** [comment]
1.27.1 已修复

**Comment by greper** [comment]
1.27.1已修复

**Comment by imluyu** [comment]
> 1.27.1已修复

![image](https://github.com/user-attachments/assets/3ae96ca1-0300-4722-8262-b350ae7bb075)

升级了新版本，仍然复现
