### ISSUE TITLE
定时触发的 crontab 是 Java 规则吗？

### ISSUE THREAD

**Issue by maxsky** [certd/certd#236]
我看了一下每两个月的 1 号执行显示的结果是 `0 0 3 1 */2 ?`

Linux 中的规则应该是 `0 3 1 */2 *`

我需要确认一下

**Comment by greper** [comment]
下方有下一次触发时间显示的，可以验证配置是否ok

![image](https://github.com/user-attachments/assets/d1cc44ed-a72c-4af2-a599-fbdd011470cb)

**Comment by maxsky** [comment]
> 下方有下一次触发时间显示的，可以验证配置是否ok
> 
> ![image](https://private-user-images.githubusercontent.com/1687298/385546201-d1cc44ed-a72c-4af2-a599-fbdd011470cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NzY0ODcsIm5iZiI6MTczMTQ3NjE4NywicGF0aCI6Ii8xNjg3Mjk4LzM4NTU0NjIwMS1kMWNjNDRlZC1hNzJjLTRhZjItYTU5OS1mYmRkMDExNDcwY2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTNUMDUzNjI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODQ5ZjFlZGRmODFjNTk3MDgyYjc2ZGUyNWQ0N2E1OTkwZDQ5MzQ5OWViYjg3NTEzN2FjZDE5OTE4OGIyZTVhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2pdfUeSBIBa86evxkfNxPZlPzjEhyzPE2p6zuQkdcfU)

应该是 Java 规则，这个规则多了秒的定义
