### ISSUE TITLE
我想要在你的插件上新增一些功能，然后使用这个插件，应该如何操作？

### ISSUE THREAD

**Issue by rideWind97** [certd/certd#24]
## 一、我想要在 上传证书到阿里云 插件上 直接绑定一个 负载均衡监听id

![image](https://github.com/certd/certd/assets/47934820/8ce33fa0-98bc-4569-8b2f-72e90f9a3c19)

本地运行是可以的，但是打包后放在服务器上后，发现这个插件没有生效，并没有出现这个 负载均衡监听id input输入框

![image](https://github.com/certd/certd/assets/47934820/4ee327f7-09dc-4508-af3b-948782c622b8)

你的代码都是用的npm包的方式，我应该如何做

#### 1. 期望效果
出现一个  负载均衡监听id input输入框
![image](https://github.com/certd/certd/assets/47934820/c5784309-e42a-4f4f-904f-6ef6eab008e0)

**Comment by greper** [comment]
你怎么打包的？

**Comment by rideWind97** [comment]
> 你怎么打包的？
![image](https://github.com/certd/certd/assets/47934820/e4718f87-6005-48a5-baf6-f993c600627c)

pnpm build & pnpm build1后

package.json中的name名我重新设置后，比如 mk-aliyun

再npm public发包


最后在certd-server中引入这个包

![image](https://github.com/certd/certd/assets/47934820/b0acd693-06df-44c0-875d-0ee74ea8a103)

但是发布后并没有生效！！！

**Comment by rideWind97** [comment]
代码打包都是正常，但是这个插件并没有生效，是我的操作方式错了还是？
我应该如何做？

**Comment by greper** [comment]
你没权限发包的，你可以把plugin build之后，将dist复制到server的node_modules对应的plugin里面，然后再打包

**Comment by greper** [comment]
> > 你怎么打包的？
> ![image](https://github.com/certd/certd/assets/47934820/e4718f87-6005-48a5-baf6-f993c600627c)
> 
> pnpm build & pnpm build1后
> 
> package.json中的name名我重新设置后，比如 mk-aliyun
> 
> 再npm public发包
> 
> 
> 最后在certd-server中引入这个包
> 
> ![image](https://github.com/certd/certd/assets/47934820/b0acd693-06df-44c0-875d-0ee74ea8a103)
> 
> 但是发布后并没有生效！！！

这里你需要 pnpm add mk-aliyun

**Comment by rideWind97** [comment]
> 你没权限发包的，你可以把plugin build之后，将dist复制到server的node_modules对应的plugin里面，然后再打包
plugin build的方式是不是   pnpm build & pnpm build1   ？

**Comment by rideWind97** [comment]
> > > 你怎么打包的？
> > > ![image](https://user-images.githubusercontent.com/47934820/273793014-e4718f87-6005-48a5-baf6-f993c600627c.png)
> > 
> > 
> > pnpm build & pnpm build1后
> > package.json中的name名我重新设置后，比如 mk-aliyun
> > 再npm public发包
> > 最后在certd-server中引入这个包
> > ![image](https://user-images.githubusercontent.com/47934820/273793496-b0acd693-06df-44c0-875d-0ee74ea8a103.png)
> > 但是发布后并没有生效！！！
> 
> 这里你需要 pnpm add mk-aliyun
mk-aliyun我这里是举例子，实际上我发布了一个mk-plugin-aliyun的包

![image](https://github.com/certd/certd/assets/47934820/5acde5bc-9e4d-4c54-ab33-0af690b3a7ea)

类型报错我不知道在哪修复，不过不影响运行
![image](https://github.com/certd/certd/assets/47934820/1719a7b2-29be-441c-9991-4f69b50c8e26)

这样打包发布后，mk-plugin-aliyun插件的功能没有生效
