### ISSUE TITLE
支持Mysql V

### ISSUE THREAD

**Issue by coolxitech** [certd/certd#240]
新建的应用建议新增安装流程，可选数据库，使用sqlite对于数据迁移不是很方便，尤其是容器。

**Comment by greper** [comment]
如果有安装流程的话， 容器里面还是没法保存数据库连接信息的

**Comment by coolxitech** [comment]
> 如果有安装流程的话， 容器里面还是没法保存数据库连接信息的

可以在.env里面提前配置

**Comment by coolxitech** [comment]
主要是我的服务器突然去世了，文件数据也没法转移，而我都是站库分离的网站，除了certd不能使用mysql其他都能恢复。

**Comment by greper** [comment]
目前支持postgres，mysql 我有空增加一下

**Comment by greper** [comment]
1.28.2已支持mysql
