### ISSUE TITLE
请求增加证书分组

### ISSUE THREAD

**Issue by helloxz** [certd/certd#247]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述

某些时候申请的证书太多了，不便于管理，建议增加证书标签或者分组功能，方便管理大量证书的情况。

### 复现步骤

无

### 报错截图
无

### 效果截图
无

**Comment by greper** [comment]
已支持
