### ISSUE TITLE
certd所在服务器的宝塔面板的baota授权部署测试失败

### ISSUE THREAD

**Issue by DukeFox** [certd/certd#248]
## 一、问题描述
已经严格按照要求填写并设置，其他服务器的baota授权均无问题，但是certd所在服务器的宝塔面板的baota授权部署缺测试失败。

### 报错截图
<img width="733" alt="屏幕截图 2024-11-26 112513" src="https://github.com/user-attachments/assets/3100e042-a682-4458-9e21-44c52d6ff20f">

**Comment by greper** [comment]
宝塔版本是9.2.0以上吗

**Comment by DukeFox** [comment]
> 宝塔版本是9.2.0以上吗

9.2.0版本

**Comment by greper** [comment]
密钥是否正确？

**Comment by DukeFox** [comment]
> 密钥是否正确？

密钥没有任何问题，其他设置包括URL什么的也没问题，白名单里也加上服务器IP了

**Comment by greper** [comment]
后台日志看看

**Comment by DukeFox** [comment]
> 后台日志看看

certd | [32m[2024-11-26T16:01:34.102] [INFO] default - [39m请求开始: /api/pi/handle/access
certd | bodyStr request_token=287aa2a94012a1e8207716dfc84a2d6f&request_time=1732608094108&cert_list=test.com
certd | [32m[2024-11-26T16:01:34.109] [INFO] default - [39mhttp request:https://83.xxx.xxx.xxx:xxxx/ssl?action=GetSiteDomain，method:post
certd | [32m[2024-11-26T16:01:34.110] [INFO] default - [39m跳过SSL验证
certd | [91m[2024-11-26T16:01:34.119] [ERROR] default - [39m请求出错：status:401,statusText:UNAUTHORIZED,url:https://83.xxx.xxx.xxx:xxxx/ssl?action=GetSiteDomain,method:post。
certd | [91m[2024-11-26T16:01:34.119] [ERROR] default - [39m返回数据: ""
certd | [91m[2024-11-26T16:01:34.120] [ERROR] default - [39m请求异常: /api/pi/handle/access 18ms HttpError [AxiosError]: 未授权，请登录
certd | at settle (file:///app/node_modules/.pnpm/axios@1.7.7_debug@4.3.7/node_modules/axios/lib/core/settle.js:19:12)
certd | at IncomingMessage.handleStreamEnd (file:///app/node_modules/.pnpm/axios@1.7.7_debug@4.3.7/node_modules/axios/lib/adapters/http.js:599:11)
certd | at IncomingMessage.emit (node:events:530:35)
certd | at endReadableNT (node:internal/streams/readable:1698:12)
certd | at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
certd | at Axios.request (file:///app/node_modules/.pnpm/axios@1.7.7_debug@4.3.7/node_modules/axios/lib/core/Axios.js:45:41)
certd | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
certd | at async x.doRequest (file:///app/node_modules/.pnpm/@certd+plugin-plus@1.27.8/node_modules/@certd/plugin-plus/dist/index.js:1:2450)
certd | at async D.onTestRequest (file:///app/node_modules/.pnpm/@certd+plugin-plus@1.27.8/node_modules/@certd/plugin-plus/dist/index.js:1:5627)
certd | at async D.onRequest (file:///app/node_modules/.pnpm/@certd+pipeline@1.27.8/node_modules/@certd/pipeline/dist/access/api.js:19:20)
certd | at async HandleController.accessRequest (file:///app/dist/controller/pipeline/handle-controller.js:43:21)
certd | at async Clz. (/app/node_modules/.pnpm/@midwayjs+core@3.17.1/node_modules/@midwayjs/core/dist/service/aspectService.js:92:34)
certd | at async /app/node_modules/.pnpm/@midwayjs+core@3.17.1/node_modules/@midwayjs/core/dist/common/webGenerator.js:43:26
certd | at async file:///app/dist/middleware/reset-passwd/middleware.js:25:13
certd | at async file:///app/dist/middleware/authority.js:76:13 {
certd | status: 401,
certd | statusText: 'UNAUTHORIZED',
certd | code: 'ERR_BAD_REQUEST',
certd | request: {
certd | baseURL: undefined,
certd | url: 'https://83.xxx.xxx.xxx:xxxx/ssl?action=GetSiteDomain',
certd | method: 'post',
certd | params: undefined,
certd | data: 'request_token=287aa2a94012a1e8207716dfc84a2d6f&request_time=1732608094108&cert_list=test.com'
certd | },
certd | response: { data: '' },
certd | cause: undefined
certd | }

**Comment by greper** [comment]
面板设置里面 API开启了吗？

**Comment by DukeFox** [comment]
> 面板设置里面 API开启了吗？

是开着的状态

**Comment by DukeFox** [comment]
> 面板设置里面 API开启了吗？

找到解决办法了，需要在本机的IP白名单里面添加`0.0.0.0`

**Comment by greper** [comment]
0.0.0.0 风险很大哦

**Comment by DukeFox** [comment]
> 0.0.0.0 风险很大哦

了解，添加`127.0.0.1`及`localhost`及本机真实IP均无法通过测试。
