### ISSUE TITLE
VoceChat通知渠道忽略证书验证

### ISSUE THREAD

**Issue by Drixn0** [certd/certd#252]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
`VoceChat通知渠道可以忽略证书验证`

### 复现步骤
`添加VoceChat通知渠道时，如果VoceChat使用https协议，添加不成功。`

### 报错截图
`![image](https://github.com/user-attachments/assets/0eb2bcc5-f410-4c06-9145-90cddae95db9)`

### 效果截图
`无`
#### 1. 期望效果
`忽略证书验证`
#### 2. 实际效果
`忽略证书验证`

**Comment by greper** [comment]
已支持
