### ISSUE TITLE
[Feature]UI界面上菜单展示的优化建议V

### ISSUE THREAD

**Issue by carolcoral** [certd/certd#255]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`

目前的菜单控制是顶部为一级菜单，点击顶部菜单后，左侧菜单才会根据点击菜单自动切换变换。
在使用的时候感觉非常别扭并不符合目前市场中常见的菜单操作方式，建议：
1. 左侧菜单使用`多级菜单`方式，左侧展示所有菜单（仅展示具备权限的菜单）
2. 取消顶部菜单，便于后续扩充别的非菜单功能按钮

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
https://element.eleme.cn/#/zh-CN/component/menu

<img width="917" alt="image" src="https://github.com/user-attachments/assets/d6295729-3d85-4943-9fcc-cc0285e4ad1a">
<img width="897" alt="image" src="https://github.com/user-attachments/assets/57b7abd9-a85d-46ea-a379-2c2dec9ac919">

**Comment by greper** [comment]
![image](https://github.com/user-attachments/assets/df6d8339-9475-4ea5-868e-e8dd2ac90b16)
左边是证书业务，右边是系统设置，这是两个大类，分开更好用，不想混到一起。
商业版菜单很多，放到一起，就需要点击展开，再滚动，更不方便
