### ISSUE TITLE
[Feature] 期望新增 Server酱³  消息推送通道

### ISSUE THREAD

**Issue by wmosys** [certd/certd#257]
## 一、问题描述
期望新增 Server酱³ 该通道与现有 Server酱Turbo 差异不大，主要相比 Turbo 版本减少了多通道推送参数，增加 Tags 标签参数。

以下是官方 API 文档：
[https://doc.sc3.ft07.com/serverchan3/server/api](https://doc.sc3.ft07.com/serverchan3/server/api)

**Comment by greper** [comment]
已支持
