### ISSUE TITLE
生成的SSL证书上传到主机后nginx报错

### ISSUE THREAD

**Issue by syuraking** [certd/certd#259]
certd是docker compose配置的，
证书保存目录为/app/data/xxx.xxx

上传主机后 nginx -t 返回以下错误：
nginx: [emerg] SSL_CTX_use_PrivateKey("/home/xxxx/.acme.sh/xxx.xxx_ecc/xxx.xxx.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed

请问一下问题出在哪儿，谢谢

**Comment by greper** [comment]
证书上传到主机配置截图看一下
注意证书保存路径是要包含文件名的

**Comment by syuraking** [comment]
已经找到原因……双方路径不匹配，重新统一了路径就好了
