### ISSUE TITLE
管理员用户看不到其他用户创建的证书自动化流水线

### ISSUE THREAD

**Issue by JiangShi-GitHub** [certd/certd#260]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
两个管理员用户，自带的admin和创建的管理员2。admin创建的自动化流水线管理员2看不见

### 复现步骤
创建管理员2并赋予管理员权限
在admin创建了两条自动化流水线任务
退出登录管理员2，在管理员2的面板里面看不见admin创建的任务。

**Comment by greper** [comment]
流水线默认只能自己看见，可以在注册设置里面把管理其他用户流水线开关打开
