### ISSUE TITLE
关于按照你们的步骤群晖无法安装的问题。

### ISSUE THREAD

**Issue by ChastityS** [certd/certd#263]
![微信图片_20241210083703](https://github.com/user-attachments/assets/12afa85c-835e-47eb-a104-08f319ed2ae1)
![微信图片_20241210084121](https://github.com/user-attachments/assets/16b07049-54a9-4df3-9932-4f9322137467)
![微信图片_20241210084126](https://github.com/user-attachments/assets/85a7ac11-0462-4441-83fb-d26c51dc76cc)
大佬按照你群辉的安装步骤我一步步操作的 但是为什么无法安装上去啊。求解答

**Comment by greper** [comment]
看具体报什么错
