### ISSUE TITLE
上传证书到主机超时

### ISSUE THREAD

**Issue by Hanson** [certd/certd#27]
## 一、问题描述
上传证书到主机超时

### 复现步骤
设置了两台机子，其中一台正常，发现超时的主机正巧是certd部署的机器，怀疑可能跟这个有关。（自己不能ssh自己？）

### 报错截图
![image](https://github.com/certd/certd/assets/10583423/93328de4-b84b-4709-8d59-6c595fa01dab)

**Comment by greper** [comment]
可以ssh自己 你可以自己在终端测试一下看行不行先

**Comment by greper** [comment]
你填的ip地址是什么？

**Comment by Hanson** [comment]
域名（指向公网），以及127都试过

**Comment by Hanson** [comment]
我也试了自己ssh自己，也是没问题的

**Comment by Hanson** [comment]
![image](https://github.com/certd/certd/assets/10583423/95ae44b8-11b4-4b97-8156-e8c7f1348bd4)
秘钥也是填写这部机子自己的秘钥

**Comment by greper** [comment]
你要用外部域名ssh，因为certd是在容器内请求的

**Comment by greper** [comment]
还要检查是否有开放安全组

**Comment by Hanson** [comment]
都试过了，不行，安全组没问题，毕竟我自己也能ssh过去

**Comment by Hanson** [comment]
已解决，参考 https://github.com/zodern/meteor-up/issues/974#issuecomment-1124494397
