### ISSUE TITLE
希望能添加支持plesk面板的证书添加 V

### ISSUE THREAD

**Issue by WeR-Best** [certd/certd#271]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
`几台主机是plesk面板，希望能添加一个开箱即用支持plesk的面板

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`

**Comment by greper** [comment]
1.29.2已支持
