### ISSUE TITLE
申请SSL证书失败报错（txt解析未创建成功）

### ISSUE THREAD

**Issue by cndomain** [certd/certd#28]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 问题描述
同一个阿里云授权账号，申请了两个SSL证书，情况如下：
cn-bamboo.com，申请失败，TXT记录未创建成功，报错见下图；
bamboogp.cn，申请成功；
初步猜测是因为域名中包含有横杠，然后代码针对域名检测机制不完善导致~

### 报错截图
![1](https://github.com/certd/certd/assets/39547357/74b2d8c5-e8a4-47c8-89df-8709631a97fe)
![2](https://github.com/certd/certd/assets/39547357/c667c25e-aa17-499d-92f3-211ce11ab0f0)
![3](https://github.com/certd/certd/assets/39547357/cae22e7e-9e1a-4bc2-9416-1c840bdb7303)

**Comment by greper** [comment]
1.20.5已修复
