### ISSUE TITLE
自定义webhook通知，url参数显示异常

### ISSUE THREAD

**Issue by linkinuul** [certd/certd#285]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
`自定义webhook通知，url参数显示异常`

### 复现步骤
自定义webhook通知

### 报错截图
<img width="285" alt="0eeb59f7a1b506903c374e40b339ba8" src="https://github.com/user-attachments/assets/02854c43-e057-4408-9fd0-9ca4295ec57d" />

### 效果截图
<img width="285" alt="0eeb59f7a1b506903c374e40b339ba8" src="https://github.com/user-attachments/assets/2a79ad45-622d-45a0-8c49-762c7a42d07b" />
#### 1. 期望效果
**应当可以显示当前站点域名**

**Comment by greper** [comment]
1.29.0已修复
