### ISSUE TITLE
mysql创建报错

### ISSUE THREAD

**Issue by xun404** [certd/certd#287]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
certd_typeorm_dataSource_default_type=mysql
启动报错
MYSQL有支持版本限制么？看着create语句不是mysql语法呀。

### 复现步骤
设置certd_typeorm_dataSource_default_type=mysql

### 报错截图
![image](https://github.com/user-attachments/assets/66b1a1c1-993b-4331-8780-ff02a4e93ce9)

**Comment by greper** [comment]
![image](https://github.com/user-attachments/assets/94a95474-7228-421b-9aa4-6df485740161)

你配置没配全

**Comment by xun404** [comment]
可以了，感谢大佬
