### ISSUE TITLE
【fix】企微提醒的@不生效

### ISSUE THREAD

**Issue by a810439322** [certd/certd#288]
![532ebd6cdc06cf55457e8d11eec5fd5](https://github.com/user-attachments/assets/07af4003-249b-42ac-83d8-dd09da0aeac0)

![53d7d07d95e8d102a394172474d3d0a](https://github.com/user-attachments/assets/8805d118-d34f-4da6-abf6-ad3c94666f4d)

**Comment by greper** [comment]
1.29.2 已修复
