### ISSUE TITLE
在代码删除域名解析后报错Authorization not found in DNS TXT record

### ISSUE THREAD

**Issue by 41369ly** [certd/certd#30]
<img width="1302" alt="image" src="https://github.com/certd/certd/assets/51309038/651d5a9f-f839-4219-b853-623be55bca20">
<img width="861" alt="image" src="https://github.com/certd/certd/assets/51309038/1d04627b-09d4-45e5-a31a-5a8524d30bf9">
测试后是因为同时申请 *.域名.cn 域名.cn导致的

**Comment by greper** [comment]
*.域名.cn, 域名.cn 不影响的

**Comment by greper** [comment]
1.20.5已修复 已优化
