### ISSUE TITLE
Certd v1.20.2 版本部分按钮点击无反应

### ISSUE THREAD

**Issue by cndomain** [certd/certd#31]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
升级到Certd v1.20.2后，很多操作按钮点不动，如下图
![1](https://github.com/certd/certd/assets/39547357/5ea8707d-1992-44a6-8152-4b3bc50b158f)
![2](https://github.com/certd/certd/assets/39547357/1617fb8a-7282-4756-b583-bc0db3122caf)
![3](https://github.com/certd/certd/assets/39547357/f7f576bb-e46f-44ef-b8c1-27eeac32290c)
同样，点击确定按钮后，原本应该关闭窗口的，也是毫无反应~

另外，提个小小的建议不知是否恰当，像下面这个列表页，是否可以增加一列显示当前证书的到期时间，这样更直观 ~
![4](https://github.com/certd/certd/assets/39547357/839ebc29-b0b7-4815-9421-3e93678d648b)

**Comment by cndomain** [comment]
官方演示站：https://certd.handsfree.work/ 问题依旧

**Comment by greper** [comment]
1.20.5已修复
