### ISSUE TITLE
希望支持百度智能云部署

### ISSUE THREAD

**Issue by muziqiu2** [certd/certd#38]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

 一、问题描述
目前在使用百度智能云的cdn，感觉要比腾讯云和阿里云的好用一些，并且相对价格比较便宜（没有htts请求数计费），所以希望如果有相对应的开发计划的话，请将百度智能云的cdn的ssl证书自动部署加入其中

**Comment by muziqiu2** [comment]
https://cloud.baidu.com/doc/CDN/s/Zkna2r57w
上面链接为百度智能云官方的更新及上传证书的api文档

**Comment by greper** [comment]
1.26.12已支持
