### ISSUE TITLE
DNS解析授权中txt记录写到另一个域名中

### ISSUE THREAD

**Issue by linzepore** [certd/certd#41]
# DNS解析授权中txt记录写到另一个域名中

## 一、问题描述
证书申请过程中，现申请了一个域名的证书之后，同一个DNS服务商（阿里云）的DNS解析授权存在txt记录写到另一个域名中，比如

## 复现步骤
申请的bar.com的证书
![image](https://github.com/certd/certd/assets/51522645/040adf53-57fe-40e4-b03b-d1989f90b461)
在foo.com的域名解析中出现了主机记录`_acme-challenge.bar.com`
![image](https://github.com/certd/certd/assets/51522645/a5f70481-500c-4b4b-8fc1-37bc8841672d)

## 报错截图

然后就导致超时了
![image](https://github.com/certd/certd/assets/51522645/34dea296-6e1a-4e2e-8348-e3b508b56208)

应该是申请的时候创建到默认那里了，我只能从foo.com把记录复制到bar.com，就可以验证并且成功了
![image](https://github.com/certd/certd/assets/51522645/9f71c50d-4e3b-4456-996b-47ac80c7d3cd)

**Comment by greper** [comment]
域名不是什么隐私信息，没必要打码，不好给你看问题

**Comment by greper** [comment]
正常来讲 解析不会到别的域名里面去
