### ISSUE TITLE
 连接服务器上传证书报错.

### ISSUE THREAD

**Issue by mingmars** [certd/certd#42]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
 连接服务器上传证书报错.

### 复现步骤
![60b3c3b2343311efb96f6039449d4e7](https://github.com/certd/certd/assets/6630251/974e71c9-c393-463f-b28d-4eaa2d949ac4)

### 报错截图
 
![b78c3e175d60c3f7a1319447956910a](https://github.com/certd/certd/assets/6630251/a83049ef-7f08-498f-ba7b-b323fe6106ce)

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
有明确的提示什么原因就好了.

**Comment by greper** [comment]
![image](https://github.com/certd/certd/assets/1687298/5037246e-ad77-41a4-a3be-587314764ea4)
