### ISSUE TITLE
但是跑了两次,在DNS解析记录都有生成,但最终流水线失败-加一个失败重试功能

### ISSUE THREAD

**Issue by mingmars** [certd/certd#43]
## 一、问题描述
但是跑了两次,在DNS解析记录都有生成,

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 报错截图
![2c5cb1d5fc12c2fc9a40639044085b7](https://github.com/certd/certd/assets/6630251/56e5f7b2-187c-4736-90d3-7879240f2180)

 这种 日志重复打了几十条之后才报错的.
![d493b42d1b9c120cd9a1084b936c411](https://github.com/certd/certd/assets/6630251/83cda33f-4878-4235-9863-b1b7df0a482e)

#### 1. 期望效果
可能需要一个异步的线程一直去处理这种 慢的问题.直到完成.或用回调方式去监控
那如果是超时的情况,就再启一次.半小时一次,一直重试?
失败后可以自动重试.时间间隔可配置.

**Comment by greper** [comment]
定时每天启动就好了，一般第二天再试就ok了
