### ISSUE TITLE
请问是否考虑支持直接将证书解压传到本机某个目录

### ISSUE THREAD

**Issue by 2ue** [certd/certd#45]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
目前使用docker在机器上部署后，想直接申请证书并解压到某个目录，并自动修改nginx配置，貌似没有插件支持，请问是否考虑支持

有两点想法：
1、增加一个支持执行shell脚本的插件，可以执行多样化的命令
2、或者局限一点，增加一个只解压拷贝证书的插件，专门把证书拷贝到某个目录下

**Comment by ZYWNB666** [comment]
这个功能已经有了，
![image](https://github.com/certd/certd/assets/104631531/cf4bf8c0-3c3f-40a6-80eb-e59c1bd12079)

**Comment by 2ue** [comment]
这个还是需要提供账号密码，我想表达的是直接在本机执行，理论上是不要账号密码的

**Comment by 2ue** [comment]
> 这个功能已经有了，
> ![image](https://github.com/certd/certd/assets/104631531/cf4bf8c0-3c3f-40a6-80eb-e59c1bd12079)
> 

我想表达的是直接在本机执行，不要输入账号密码

**Comment by greper** [comment]
1.20.11 上传证书到主机插件，已支持复制证书到当前主机的某个目录。由于docker启动的，所以需要在docker-compose.yaml配置目录映射
