### ISSUE TITLE
Docker简化

### ISSUE THREAD

**Issue by superlbr** [certd/certd#46]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
1. 不需要docker compose，一个dockerfile就足够了。这样还有利于镜像分发。
2. docker build出来镜像很大，certd-server build之后，只需要dist就可以了。。参考[midway部署](https://www.midwayjs.org/docs/deployment#%E7%BC%96%E5%86%99-dockerfile%E6%9E%84%E5%BB%BA%E9%95%9C%E5%83%8F)

**Comment by greper** [comment]
不需要你build的

**Comment by greper** [comment]
你用docker/run目录下的docker-compose直接运行就行

**Comment by superlbr** [comment]
是的，其实一个docker run也可以。
