### ISSUE TITLE
申请证书失败

### ISSUE THREAD

**Issue by molixiaoge** [certd/certd#47]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`
配置阿里云accesskey 手动申请证书失败,用户添加了dns相关权限
### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 报错截图
`请贴出报错日志截图`
![图片](https://github.com/certd/certd/assets/1323533/a33c4d29-9340-4313-9a57-b0d6d2b2ddc1)

### 效果截图
`请贴出效果截图`

**Comment by greper** [comment]
你删除了引用的授权记录，所以无法申请
