### ISSUE TITLE
希望支持部署到华为云CDN

### ISSUE THREAD

**Issue by graphenn** [certd/certd#48]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
希望支持部署到华为云CDN。现在从华为云DNS申请证书已经支持了，大部分流程都打通啦，部署希望也能支持上。
我不会搞js，只能看看流程。步骤大致是
ShowCertificatesHttpsInfo,基于domain_name，查出原有属性
UpdateDomainMultiCertificates，参考上面查出来的各个属性，以及新的证书，配置进去

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`

**Comment by greper** [comment]
1.27.1已支持

**Comment by graphenn** [comment]
感谢

**Comment by graphenn** [comment]
非常感谢 @greper 的工作，没有第一时间关闭这个单，我是想测试验证一下。今天花时间验了下我用的几个域名，部署都没问题，缓存配置、https配置等都不会丢失。赞
