### ISSUE TITLE
cert.zip 名字能改一下吗

### ISSUE THREAD

**Issue by molixiaoge** [certd/certd#49]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`
多证书，每个都是cert.zip导致无法区分，能加上域名和申请的日期么？

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`

**Comment by greper** [comment]
1.20.11已支持

**Comment by molixiaoge** [comment]
试了一下 1.20.11 ，可以下载对应的名字了。
首页显示的版本号不一致 
![图片](https://github.com/certd/certd/assets/1323533/1fb409e6-8f1d-49c5-bb95-44d6b1ed081c)
