### ISSUE TITLE
多证书定时触发不同步

### ISSUE THREAD

**Issue by molixiaoge** [certd/certd#52]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`
设置了三个证书，每周三凌晨执行更新，但是只有一个证书更新了。
### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 报错截图
`请贴出报错日志截图`

![图片](https://github.com/certd/certd/assets/1323533/b87ce5e0-7368-42ba-99af-94588e3d9727)

![图片](https://github.com/certd/certd/assets/1323533/16ff3c6f-a71b-4675-8cae-a040fd54ff90)

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
三个证书每周三凌晨同时更新

**Comment by greper** [comment]
过期前20天才会更新证书

**Comment by molixiaoge** [comment]
是别的任务定时都没执行，
![图片](https://github.com/certd/certd/assets/1323533/cbfd7c74-f149-423a-aed5-4b31924341bd)

同样的定时触发规则
![图片](https://github.com/certd/certd/assets/1323533/2e981def-eb5b-4273-b6a2-a5bf82f3610f)
没有执行日志
