### ISSUE TITLE
前端界面希望能够显示证书剩余天数

### ISSUE THREAD

**Issue by iStarCc** [certd/certd#54]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
`前端界面希望能够显示证书剩余天数，这样可以判断证书是否已经续期成功或者手动申请的当前剩余天数`

**Comment by ma3252788** [comment]
同求

**Comment by XiaoPika** [comment]
同求，实际上就是证书监控服务，同样可以调用已经配置的邮箱进行提醒

**Comment by greper** [comment]
剩余天数已支持
后续计划增加网站证书监控功能

**Comment by XiaoPika** [comment]
感谢作者！为您赞美！给您老婆打款！

**Comment by greper** [comment]
可以爱发电赞助 获得专业版激活码哟
