### ISSUE TITLE
如何修改默认的7001端口？和群晖的fileStation端口冲突了

### ISSUE THREAD

**Issue by hicaoc** [certd/certd#57]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
`端口冲突，7001已经被其他程序占用`

### 复现步骤
`请描述复现问题的详细步骤`
`需要修改端口号`

**Comment by greper** [comment]
![image](https://github.com/certd/certd/assets/1687298/f2881c9f-3162-465e-82cd-cff426f9aa36)
