### ISSUE TITLE
可以支持上传到群晖的证书码？acme支持调用群晖的api更新群晖的证书了

### ISSUE THREAD

**Issue by hicaoc** [certd/certd#58]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

希望能支持更新群晖的证书

**Comment by greper** [comment]
群晖是什么软件，api文档链接发一下

**Comment by glennbel2000** [comment]
群晖可以使用如下脚本搭配certd一同服用：
https://github.com/glennbel2000/syno_cert_renewal_shell

**Comment by ui-beam-9** [comment]
> 群晖可以使用如下脚本搭配certd一同服用： https://github.com/glennbel2000/syno_cert_renewal_shell

这个脚本的前提是证书得传到群晖上，但是现在通过certd证书是无法传输到群晖的，现在需要解决的是怎么把证书传到群晖上

**Comment by greper** [comment]
群晖到底是个啥玩意

**Comment by ui-beam-9** [comment]
> 群晖到底是个啥玩意

群晖是一个制作网络存储（NAS）设备的公司，旗下的DSM系统现在非常火
这里把官网贴出来：https://www.synology.cn/zh-cn
因为我刚刚试了下直接上传证书到群晖，就算在控制面板开启了SFTP，实际还是无法上传的
![微信图片_20240715134318](https://github.com/user-attachments/assets/db0ca403-7547-4ebe-b1a6-480e727f1c72)

**Comment by ui-beam-9** [comment]
现在只需要加一个在上传证书时可以选择什么协议上传就行，像群晖就是支持SCP协议的

**Comment by cuicsi** [comment]
需求➕1，昨天试了没弄好。想到一个方法就是上传到服务器，然后同步到群晖。应该可以实现，晚上试一下

**Comment by glennbel2000** [comment]
使用群晖的账号权限，设置允许sftp应用以及打开sftp端口，然后certd更新最新版本设置证书上传主机，不要创建目录，证书文件fullchain.pem
，密钥文件priviatekey.pem









Glenn&nbsp;Chen

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月15日(周一) 中午1:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [certd/certd] 可以支持上传到群晖的证书码？acme支持调用群晖的api更新群晖的证书了 (Issue #58)




 
现在只需要加一个在上传证书时可以选择什么协议上传就行，像群晖就是支持SCP协议的

**Comment by glennbel2000** [comment]
使用群晖的账号权限，设置允许sftp应用以及打开sftp端口，然后certd更新最新版本设置证书上传主机，不要创建目录，证书文件fullchain.pem
，密钥文件privikey.pem

![image](https://github.com/user-attachments/assets/2a77d4b3-0bee-4187-b4ae-d49f086fc6c8)

**Comment by glennbel2000** [comment]
群晖内设置如下：
![image](https://github.com/user-attachments/assets/0cc048dc-96ce-46bb-a910-0b2ec8eeb602)

![image](https://github.com/user-attachments/assets/70f3db07-c373-40cc-8ea7-8702af84e3e1)

**Comment by ui-beam-9** [comment]
> 使用群晖的账号权限，设置允许sftp应用以及打开sftp端口，然后certd更新最新版本设置证书上传主机，不要创建目录，证书文件fullchain.pem ，密钥文件privikey.pem
> 
> ![image](https://private-user-images.githubusercontent.com/174859042/348612408-2a77d4b3-0bee-4187-b4ae-d49f086fc6c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjUwNzYsIm5iZiI6MTcyMTAyNDc3NiwicGF0aCI6Ii8xNzQ4NTkwNDIvMzQ4NjEyNDA4LTJhNzdkNGIzLTBiZWUtNDE4Ny1iNGFlLWQ0OWYwODZmYzZjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwNjI2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2ZjZWQ2MmFjNDkwYWY2OWY4NWYxZDQxMmZiMzI1MTcxODAzOGE4ZTRkNDNjYTc2ZGY2YzNiOTdmNTZkYzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lnjH85oU518qWVx3fabsn247xF9ZbO1ERY4zmzf7eB4)

你好，我按照你的方法试了一下，用户是新创建的，权限也是按照图里给的，但是还是报错了，是我哪个步骤不对吗，还请大佬看看
![image](https://github.com/user-attachments/assets/4db97fda-c308-4963-bb1f-fd0bc34b4a09)
![image](https://github.com/user-attachments/assets/f273cb42-6c96-49b0-a1e4-79aecf17ab44)
![image](https://github.com/user-attachments/assets/61afa74d-c61d-41bf-9ea4-4ea28cf31b14)
![image](https://github.com/user-attachments/assets/dd5a8e47-55af-4c8d-b0d4-74fb9b1cb5fd)

**Comment by glennbel2000** [comment]
群晖用户的sftp的根目录是/home，如certd账户的真实根目录为/volume1/homes/certd/但是在sftp内根目录就是/home/，参考我的截图

**Comment by glennbel2000** [comment]
> 群晖sftp的根目录是/home，参考我的截图

不是/volume1这种，这个要root权限才能访问

**Comment by ui-beam-9** [comment]
> 群晖用户的sftp的根目录是/home，如certd账户的真实根目录为/volume1/homes/certd/但是在sftp内根目录就是/home/，参考我的截图

可以了，把路径一改就直接上传成功了，感谢！！！，另外我还把重载脚本也加在了自动化里，但是这个脚本目前只能做到上传证书，每次上传之后都要到控制面板里手动改一下证书才能生效，想问一下这个有什么办法可以让他自动修改，或者是直接覆盖原有的，这个有官方的文档说明吗？如果有的话，麻烦能提供一下吗？
![image](https://github.com/user-attachments/assets/ec26e6cc-697b-4383-98d8-4f9f38e1f6b3)

**Comment by glennbel2000** [comment]
群晖里面的设置看这里（定期脚本，比certd晚几分钟就可以了）https://github.com/glennbel2000/syno_cert_renewal_shell

**Comment by greper** [comment]
1.24.4已支持
