### ISSUE TITLE
账号密码忘记了怎么办

### ISSUE THREAD

**Issue by guicaiyue** [certd/certd#59]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
太久没管忘记账号密码了

### 复现步骤
太久没管忘记账号密码了

#### 2. 实际效果
进入容器，指定目录找到账号密码

**Comment by greper** [comment]
我后续写个重置密码的脚本吧
临时解决方案
1. 注册一个小号，然后关闭服务
2. 然后复制 /data/certd/db.sqlite数据文件到本地
3. 找个sqlite管理工具打开它，找到sys_user表，将小号的密码复制到大号上去
4. 然后复制回服务器上，启动服务，用小号的密码登录

**Comment by greper** [comment]
https://github.com/certd/certd?tab=readme-ov-file#21-%E5%BF%98%E8%AE%B0%E7%AE%A1%E7%90%86%E5%91%98%E5%AF%86%E7%A0%81

1.20.12版本，新增重置密码功能
