### ISSUE TITLE
没有对应的任务

### ISSUE THREAD

**Issue by 0zjn0123** [certd/certd#6]
部署流程没有对应的任务：
![image](https://user-images.githubusercontent.com/116432703/212026024-d5161558-2cc5-4bbe-8ca1-9712d0f009d5.png)

![](https://user-images.githubusercontent.com/116432703/212025595-0fd9a04d-2067-4ffd-a3f4-11f00f7ecd18.png)

**Comment by greper** [comment]
不懂你想要问什么

**Comment by 0zjn0123** [comment]
这个网站坏掉了，一直添加不了授权

**Comment by 0zjn0123** [comment]
> 不懂你想要问什么

这个网站坏掉了，一直添加不了授权

**Comment by greper** [comment]
我这边测试没有问题，你得把问题说详细一点，加上截图

**Comment by 0zjn0123** [comment]
> 我这边测试没有问题，你得把问题说详细一点，加上截图

就是在编辑授权里填完信息以后点“确定”没有反应

**Comment by greper** [comment]
用chrome浏览器

**Comment by 0zjn0123** [comment]
> 用chrome浏览器

用的就是chrome浏览器

**Comment by greper** [comment]
截个图啊

**Comment by 0zjn0123** [comment]
![image](https://user-images.githubusercontent.com/116432703/212029050-c12d12cd-fb3e-4f1c-8390-7224af9444fe.png)


> 截个图啊

**Comment by 0zjn0123** [comment]
> 截个图啊

![](https://user-images.githubusercontent.com/116432703/212029171-278df2e7-41c4-4a88-9d09-dab28cffdcbe.png)

**Comment by greper** [comment]
我这边测试没有问题，你升级一下chrome试试，或者换edge浏览器

**Comment by 0zjn0123** [comment]
> 我这边测试没有问题，你升级一下chrome试试，或者换edge浏览器

哦，我试试

**Comment by 0zjn0123** [comment]
> 我这边测试没有问题，你升级一下chrome试试，或者换edge浏览器

我待会再试

**Comment by greper** [comment]
请使用v2版本
