### ISSUE TITLE
新增ssl证书提供商（例如 Google、ZeroSSL ）

### ISSUE THREAD

**Issue by fx-k** [certd/certd#60]
是否考虑支持更多的SSL证书提供商，例如Google、ZeroSSL等，也是基于acme申请的。

**Comment by greper** [comment]
不明白为什么一定要这两个提供商？

**Comment by whitiy666** [comment]
> 不明白为什么一定要这两个提供商？

lets的兼容性很差，尤其是app里面的api，在低版本安卓里面直接不可信

**Comment by greper** [comment]
1.21.0 已支持zerossl。
google的证书找不到文档，你可以发一下google的文档链接吗

**Comment by kairlec** [comment]
> 1.21.0 已支持zerossl。 google的证书找不到文档，你可以发一下google的文档链接吗

https://cloud.google.com/certificate-manager/docs/public-ca-tutorial?hl=zh-cn

**Comment by netputer** [comment]
是否可以把 acme.sh 的参数开放出来，一个好处是 acme.sh 支持的证书品牌在 certd 也自然支持，另一个是如果平台支持 acme 那么 certd 也能支持

**Comment by greper** [comment]
已经支持lego，稍候发布新版本

**Comment by greper** [comment]
1.24.1已支持
