### ISSUE TITLE
能否增加自动部署到宝塔呀？

### ISSUE THREAD

**Issue by ma3252788** [certd/certd#61]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`

大佬好，请问支持将申请的证书自动部署到宝塔面板的站点上吗？我之前以为这个仓库是可以自动续时间，今天翻了issue才发现原来这个是新申请证书的。所以能不能支持申请证书之后自动部署到宝塔的站点上呢？

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

1. 申请证书
2. 自动部署

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
#### 1. 期望效果

能够自动部署到宝塔

#### 2. 实际效果

目前好像只支持部署到服务器

**Comment by fx-k** [comment]
这个自己部署就行了，很简单的。传到本地目录，然后执行主机命令：/etc/init.d/nginx reload

**Comment by superlbr** [comment]
宝塔可以自动续期的，SSL选项里Let's Encrypt

**Comment by greper** [comment]
用上传证书到服务器 和 执行主机命令插件 执行部署任务
然后设置每天定时执行，就可以实现证书自动续期、自动部署

**Comment by ma3252788** [comment]
感谢各位，已经可以了，我是先上传到阿里云服务器，然后用宝塔的api替换的ssl证书。
我试了直接替换vhost目录下的ssl文件，然后重启Nginx，宝塔网站列表中还是原来的ssl时间，所以就用api替换了。
