### ISSUE TITLE
BUG：主机配置OPENSSH非加密私钥会导致上传证书到主机一直运行

### ISSUE THREAD

**Issue by vseal001** [certd/certd#65]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
主机配置OPENSSH非加密私钥会导致上传证书到主机一直运行`

### 复现步骤
粘贴如下私钥到主机配置中的密钥：
[私钥及对应公钥.zip](https://github.com/user-attachments/files/15873005/default.zip)

### 报错截图
![openssh私钥](https://github.com/certd/certd/assets/35253928/ad0390cf-53c6-4d1e-9256-b3897491f91c)
![openssh私钥-上传进行中](https://github.com/certd/certd/assets/35253928/a5071c0e-28b7-4c63-8e84-530d7a97136c)
![openssh私钥-上传进行中1](https://github.com/certd/certd/assets/35253928/dbc948e1-0c42-4a2e-ada4-5aeff4cb4333)

**Comment by greper** [comment]
用1.20.12版本试试

**Comment by vseal001** [comment]
问题找到呢，DEBIAN12系统SSH默认不支持RSA的密钥，解决措施如下：
具体的解决方法很简单，在```/etc/ssh/sshd_config```中添加：

```
PubkeyAcceptedKeyTypes +ssh-rsa
```

然后重启ssh服务即可：

```
systemctl restart sshd
```

再使用CERTD上传证书到主机就正常了。

但是CERTD本身应该设置主机验证超时吧，还请麻烦看看。
