### ISSUE TITLE
修改密码时报错

### ISSUE THREAD

**Issue by gituib** [certd/certd#70]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
修改密码时报错

Cannot read properties of undefined (reading 'getFormData')

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 报错截图
![image](https://github.com/certd/certd/assets/35016327/42c5f92a-1a37-4b22-99c0-db014a051c35)

### 效果截图
`请贴出效果截图`

**Comment by appig** [comment]
同样问题，怎么解决？

**Comment by greper** [comment]
1.20.14已修复
