### ISSUE TITLE
上传到主机能否支持Windows

### ISSUE THREAD

**Issue by ltxhhz** [certd/certd#73]
## 一、问题描述

已配置私钥登录
似乎不支持 `Windows`，命令行是 `powershell`
日志中显示执行了`mkdir -p .`，但是在Windows会报错 `mkdir : 具有指定名称 C:\Users\Administrator` 的项已存在。`
这个错误可以忽略，但也没有继续执行

### 报错截图
![image](https://github.com/certd/certd/assets/51697596/ab95d952-9511-4273-8155-c33f8b7ebcdd)

### 复现步骤
选择上传证书到主机，目标主机为 `Windows` 时

**Comment by greper** [comment]
1.20.15已支持

**Comment by ltxhhz** [comment]
还是同样的问题 @greper 
![image](https://github.com/certd/certd/assets/51697596/44ebfbf1-462d-4f4d-abe1-9b0d3418fc52)

**Comment by ltxhhz** [comment]
> ## 一、问题描述
> 已配置私钥登录 似乎不支持 `Windows`，命令行是 `powershell` 日志中显示执行了`mkdir -p .`，但是在Windows会报错 `mkdir : 具有指定名称 C:\Users\Administrator` 的项已存在。` 这个错误可以忽略，但也没有继续执行
> 

不好意思，我刚看源码才注意到授权管理新加的"是否Windows"选项，但是我最开始也说明了目标主机的命令行是powershell，直接执行 `if not exist "." mkdir  .` 是不行的，我的建议是 使用 `echo %COMSPEC%` 先判断命令行，再根据命令行来执行命令

![image](https://github.com/certd/certd/assets/51697596/376bb481-58da-47b1-af5e-8aa312d2f881)

**Comment by greper** [comment]
为什么目标目录是 . ?

**Comment by ltxhhz** [comment]
原本的代码就这么写的，filePath是个变量

**Comment by greper** [comment]
如果是. 就无需创建就行了， 目标目录如果不是.  ， powershell 里面可以执行 mkdir -p xxx的

**Comment by greper** [comment]
所以你的pr 搞复杂了

**Comment by greper** [comment]
已合并
