### ISSUE TITLE
docker更新后，前端界面还是显示1.20.9的版本

### ISSUE THREAD

**Issue by cc4dogman** [certd/certd#83]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
已更新到1.21.1版本

### 复现步骤
直接修改docker镜像版本

### 报错截图
![image](https://github.com/certd/certd/assets/3928242/5c3a51b0-f2b7-4402-9147-56f00783f551)
![image](https://github.com/certd/certd/assets/3928242/731e638e-a7fc-4df5-a79c-6970a50f836f)

**Comment by greper** [comment]
Ctrl+F5 刷新页面

**Comment by cc4dogman** [comment]
Ctrl+F5,忽略缓存，重启docker容器都试过，还是不行，看了docker里面的package.json确实是新版本号，但界面上还是老的版本
![image](https://github.com/certd/certd/assets/3928242/9cd5b4d6-875b-432a-b5c7-1c19a1e24562)

**Comment by cc4dogman** [comment]
直接访问ip可以看到新版本，此贴终结
