### ISSUE TITLE
AxiosError: getaddrinfo EAI_AGAIN acme-v02.api.letsencrypt.org

### ISSUE THREAD

**Issue by meesii** [certd/certd#88]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
申请证书的时候出错如下截图报错：
AxiosError: getaddrinfo EAI_AGAIN acme-v02.api.letsencrypt.org
但是我尝试访问这个域名是可以打开的

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 报错截图
![image](https://github.com/user-attachments/assets/b7d5060f-2484-4439-9e93-2da10cc24781)

### 效果截图
`请贴出效果截图`

**Comment by meesii** [comment]
![image](https://github.com/user-attachments/assets/422c2570-7b72-4c43-9450-ef0152902656)

这是底下部分的报错代码

**Comment by greper** [comment]
你宿主机无法访问 letsencrypt.org 先解决网络问题
