### ISSUE TITLE
希望能增加自动化部署雷池WAF证书这个功能

### ISSUE THREAD

**Issue by ui-beam-9** [certd/certd#92]

**Comment by HTTtengvv** [comment]
这个很简单，写个shell脚本。
雷池站点ssl证书目录：/data/safeline/resources/nginx/certs
替换原证书后（名字要与原来保持一致）
重载一下雷池的nginx： docker exec -i safeline-tengine /bin/bash -c 'nginx -s reload'

**Comment by h31105** [comment]
雷池WAF 自身就支持吧

**Comment by cgh1999520** [comment]
支持直接雷池部署，雷池证书目录：/data/safeline/resources/nginx/certs/ ，先手动添加一个证书，然后再用certd 证书上传去覆盖原证书文件就可以实现。亲测可用

**Comment by greper** [comment]
已有解决方案，关闭issue

**Comment by greper** [comment]
1.29.2已支持
