### ISSUE TITLE
部署到阿里云AckIngress出错

### ISSUE THREAD

**Issue by MatcherAny** [certd/certd#95]
## 一、问题描述
使用的是certd1.21.2, 阿里云Access授权可以正常上传到阿里云, 但是部署到阿里云AckIngress反复提示相同的错误

流水线配置如下
![image](https://github.com/user-attachments/assets/ffe023cf-2f31-437f-bcae-3e6d08c4d19d)

### 报错截图
![K86HOHW 2Q(T~QXEQA~(F8Q](https://github.com/user-attachments/assets/84bc5e8d-4a5e-4e1f-bc6c-8689eed23fc0)

完整日志文件如下
[logs.txt](https://github.com/user-attachments/files/16261939/logs.txt)

**Comment by greper** [comment]
1.25.5已修复
