### ISSUE TITLE
userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]

### ISSUE THREAD

**Issue by Ansen** [certd/certd#96]
## 一、问题描述
向主机上传证书失败, 报错

`Error: All configured authentication methods failed`

服务器(ubuntu 22.04) ssh 日志:
```
userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
```

原因, certd 的 Alpine Linux 3.17 中的 openssh 版本过低

解决方法: 
1. 请使用最新的 node:18-alpine 镜像进行构建 (**推荐**), 
  - 已使用 docker hub 上的最新镜像(Alpine Linux 3.20)进行ssh 连接测试,  无此问题
3. 在服务器修改sshd的配置 添加 ssh-rsa 协议支持

### 复现步骤

向系统为 ubuntu.2204的服务器上传证书即可复现

### 报错截图

> certd 日志
![image](https://github.com/user-attachments/assets/1049262b-17a7-4991-8ed2-d686d5f7006b)

> 服务器 ssh 日志

![image](https://github.com/user-attachments/assets/3cd2c4b1-ed7d-4b0a-a48f-98728ce7824a)

**Comment by greper** [comment]
已使用最新的node镜像

**Comment by leiwcq** [comment]
使用 2024-08-06 11:41:29 的镜像 登录Ubuntu 24.04主机仍会报此错误

**Comment by drinktea1a** [comment]
使用xshell客户端可以基于私钥登录，但是流水线里，始终提示失败
![Snipaste_2024-08-19_14-02-03](https://github.com/user-attachments/assets/43fa97e1-30b8-4a74-b3d2-d30ae5e3617f)
