### ISSUE TITLE
能否增加京东云DNS或支持手动解析dns

### ISSUE THREAD

**Issue by yy9** [certd/certd#98]
## 希望增加京东云DNS的支持
 京东云DNS接口文档
https://docs.jdcloud.com/cn/jd-cloud-dns/api/introduction
 其他(参考acmesh-official)
 https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_jd.sh

**Comment by greper** [comment]
1.27.2版本，cname方式，已支持所有域名注册商
