### ISSUE TITLE
希望能增加对阿里云dcdn、oss域名证书续期的功能

### ISSUE THREAD

**Issue by wabksw** [certd/certd#99]
#### 阿里云oss api文档：https://help.aliyun.com/zh/oss/developer-reference/api-reference/?spm=a2c4g.11174283.0.0.30337368HihVku

**Comment by Fierce-Cat** [comment]
经测试，只需要选择部署至阿里云CDN，并填写DCDN地址，就可以自动部署新的证书。

**Comment by wujingke** [comment]
已经支持了
